CREATE TABLE IF NOT EXISTS PostLike (
  id TEXT PRIMARY KEY NOT NULL,
  postId TEXT NOT NULL,
  userId TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS PostLike_postId_userId_key ON PostLike(postId, userId);

CREATE TABLE IF NOT EXISTS PostComment (
  id TEXT PRIMARY KEY NOT NULL,
  postId TEXT NOT NULL,
  userId TEXT NOT NULL,
  body TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS PostComment_postId_createdAt_idx ON PostComment(postId, createdAt);

CREATE TABLE IF NOT EXISTS DirectMessage (
  id TEXT PRIMARY KEY NOT NULL,
  fromUserId TEXT NOT NULL,
  toUserId TEXT NOT NULL,
  body TEXT NOT NULL,
  readAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fromUserId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (toUserId) REFERENCES User(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS DirectMessage_to_created_idx ON DirectMessage(toUserId, createdAt);
CREATE INDEX IF NOT EXISTS DirectMessage_pair_idx ON DirectMessage(fromUserId, toUserId, createdAt);
